<?php
/**
 * cada.module
 *
 * CADA customization
 *
 * @category   Drupal module
 * @package    CADA
 * @author     Graham Stratford
 * @copyright  2019 Graham Stratford
 * @license    http://www.php.net/license/3_0.txt  PHP License 3.0
 * @version    CVS: $Id:$
 */

define('CADA_DEALER', 'cada_dealer');

/**
 * Display the dealer information
 *
 * @param integer $dealerID
 * @param bool $linkToAntiqueItems
 */
function cada_renderDealer($dealerID, $linkToAntiqueItems = false) {
  $dealer = user_load($dealerID);

  $wrapper = entity_metadata_wrapper('user', $dealer);
  $d = array(
    'id' => $linkToAntiqueItems ? $dealerID : null,
    'name' => $wrapper->field_dealer_name->value(),
    'address' => $wrapper->field_address->value(),
    'phone' => $wrapper->field_phone->value(),
    'email' => $dealer->mail,
    'fax' => $wrapper->field_fax->value(),
    'web' => $wrapper->field_web->value(),
    'contact' => $wrapper->field_full_name->value(),
  );
  print(theme(CADA_DEALER, array('user' => $d)));
}

/**
 * Implementation of hook_theme()
 *
 * @return array
 */
function cada_theme() {
  return (array(
    CADA_DEALER => array(
      'variables' => array('user' => NULL),
      'template' => 'templates/dealer'
    ),
  ));
}
